# Generated by Django 4.1.7 on 2023-03-11 15:29

from django.db import migrations


def create_roles(apps, schema_editor):
    Role = apps.get_model('user', 'Role')
    roles = [Role(name='ghost'), Role(name='player')]
    for role in roles:
        role.save()


class Migration(migrations.Migration):
    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(create_roles),
    ]
