# Generated by Django 4.1.7 on 2023-04-02 22:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('bingo', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GameSession',
            fields=[
                ('game_id', models.IntegerField(primary_key=True, serialize=False)),
                ('launched', models.BooleanField(default=False)),
                ('join_code', models.TextField(default='1q2w3e4r', unique=True)),
                ('bingo_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bingo.bingo')),
            ],
        ),
    ]
