# Generated by Django 4.1.7 on 2023-03-14 22:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('bingo', '0002_bingo_author_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='GameSession',
            fields=[
                ('game_id', models.IntegerField(primary_key=True, serialize=False)),
                ('launched', models.BooleanField(default=False)),
                ('max_players', models.IntegerField(null=True)),
                ('bingo_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bingo.bingo')),
            ],
        ),
    ]
