# Generated by Django 4.1.7 on 2023-03-24 22:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gamesession',
            name='max_players',
        ),
        migrations.AddField(
            model_name='gamesession',
            name='join_code',
            field=models.TextField(default='1q2w3e4r', unique=True),
        ),
    ]
