# Generated by Django 4.1.7 on 2023-03-13 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bingo',
            fields=[
                ('bingo_id', models.IntegerField(auto_created=True, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('words', models.TextField()),
            ],
        ),
    ]
