# Generated by Django 4.1.7 on 2023-03-15 22:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_session', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usersession',
            name='random_seed',
            field=models.IntegerField(default=7637),
        ),
    ]
