# Generated by Django 4.1.7 on 2023-03-24 22:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_session', '0002_alter_usersession_random_seed'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usersession',
            name='id',
        ),
        migrations.AddField(
            model_name='usersession',
            name='session_id',
            field=models.IntegerField(default=-1, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='usersession',
            name='random_seed',
            field=models.IntegerField(default=5755),
        ),
    ]
