# Generated by Django 4.1.7 on 2023-03-24 22:52

from django.db import migrations, models
import django.db.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('user_session', '0003_remove_usersession_id_usersession_session_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usersession',
            name='random_seed',
            field=models.IntegerField(default=9584),
        ),
        migrations.AlterField(
            model_name='usersession',
            name='session_id',
            field=models.IntegerField(default=django.db.models.fields.AutoField, primary_key=True, serialize=False),
        ),
    ]
