# Generated by Django 4.1.7 on 2023-03-24 22:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_session', '0004_alter_usersession_random_seed_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usersession',
            name='random_seed',
            field=models.IntegerField(default=9600),
        ),
        migrations.AlterField(
            model_name='usersession',
            name='session_id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
